version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - intranet

  pgadmin:
    image: adminer:latest
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - intranet

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.compose
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - 1337:1337
    depends_on:
      - db
    networks:
      - intranet
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.env:/app/.env
      - ./public/uploads:/app/public/uploads
      - ./types:/app/types
networks:
  intranet:
    driver: bridge
